#pragma once
#define BANNER_ASCII "SOVRN ENGINE ONLINE | VERSION=v0.0.0-forge | COMMIT= | EPOCH=1758487672 | TRIPLE= | TOOLCHAIN="
#define BANNER_WIDE  L"SOVRN ENGINE ONLINE | VERSION=v0.0.0-forge | COMMIT= | EPOCH=1758487672 | TRIPLE= | TOOLCHAIN="
#define BANNER_PRODUCT   L"SOVRN OS"
#define BANNER_VERSION   L"v0.0.0-forge"
#define BANNER_COMMIT    L""
#define BANNER_EPOCH     L"1758487672"
#define BANNER_TRIPLE    L""
#define BANNER_TOOLCHAIN L""
