name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set deterministic env
        run: |
          echo "SOURCE_DATE_EPOCH=1734825600" >> $GITHUB_ENV
          echo "LC_ALL=C" >> $GITHUB_ENV

      - name: Toolchain
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y \
            build-essential binutils xorriso mtools dosfstools uuid-dev \
            gnu-efi ovmf qemu-system-x86 qemu-utils

      - name: Build
        run: make

      - name: Build ISO
        run: make iso

      - name: Size gate (kernel ≤ 512 KiB)
        run: ./scripts/size_gate.sh kernel.bin 524288

      - name: ISO size gate (≤ 32 MiB, conditional)
        run: |
          if [ -f iso/sovrn.iso ]; then
            ./scripts/size_gate.sh iso/sovrn.iso 33554432
          else
            echo "No ISO yet — skipping"
          fi

      - name: Rebuild EFI/ISO for smoke (exit after banner)
        run: |
          EFI_DEFINES="-DSOVRN_EXIT_AFTER_BANNER" bash scripts/build_efi.sh
          make iso

      - name: UEFI smoke (serial)
        run: |
          set -euxo pipefail
          rm -f out/qemu-uefi-serial.log out/smoke_result.txt || true
          if scripts/boot_smoke.sh iso/sovrn.iso; then
            echo PASS > out/smoke_result.txt
          else
            echo FAIL > out/smoke_result.txt
          fi
          exit 0  # always upload logs

      - name: Upload serial log + result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: uefi-smoke
          path: |
            out/qemu-uefi-serial.log
            out/smoke_result.txt
          if-no-files-found: warn

      - name: Assert smoke passed
        run: grep -q PASS out/smoke_result.txt

      - name: EFI verify (conditional)
        run: bash scripts/efi_verify.sh || true

      - name: SHA256SUMS
        run: ./scripts/mksums.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: phase-artifacts
          path: |
            kernel.bin
            out/BUILDINFO
            out/BANNER.txt
            out/SHA256SUMS
            iso/sovrn.iso
            boot/BOOTX64.EFI
            boot/mbr.bin
          if-no-files-found: warn
