name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set deterministic env
        run: |
          echo "SOURCE_DATE_EPOCH=1734825600" >> $GITHUB_ENV
          echo "LC_ALL=C" >> $GITHUB_ENV
      - name: Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential xorriso mtools dosfstools gnu-efi gnu-efi-amd64