name: Gate 2A — Smoke (BIOS+UEFI)

on:
  push:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install host deps (QEMU + OVMF)
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq qemu-system-x86 ovmf xorriso

      - name: Build tool image
        run: docker build -t sovrn-efi .

      - name: Build BIOS+UEFI and ISO inside container
        run: |
          set -euxo pipefail
          docker run --rm -v "$PWD":/work -w /work --entrypoint /bin/sh sovrn-efi -euxc '
            scripts/buildinfo.sh
            scripts/build_bios.sh
            scripts/build_uefi.sh
            scripts/esp_sync.sh
            scripts/mkiso.sh
          '
          ls -lh iso/sovrn.iso out/stage2.bin boot/BOOTX64.EFI
          test -s iso/sovrn.iso

      - name: BIOS smoke (legacy, capture serial)
        run: |
          set -euxo pipefail
          touch bios.log
          timeout 25s qemu-system-i386 \
            -machine pc,accel=tcg -display none -no-reboot \
            -serial stdio \
            -cdrom "$PWD/iso/sovrn.iso" -boot order=d \
            | tee bios.log || true
          test -e bios.log

      - name: UEFI smoke (OVMF, capture serial)
        run: |
          set -euxo pipefail
          cp /usr/share/OVMF/OVMF_VARS.fd ./OVMF_VARS.fd
          touch uefi.log
          timeout 25s qemu-system-x86_64 \
            -machine q35,accel=tcg -display none -no-reboot \
            -serial stdio \
            -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_CODE.fd \
            -drive if=pflash,format=raw,file="$PWD/OVMF_VARS.fd" \
            -cdrom "$PWD/iso/sovrn.iso" -boot order=d,menu=off \
            | tee uefi.log || true
          test -e uefi.log

      - name: Assert banner on both paths
        run: |
          set -eux
          grep -F "SOVRN ENGINE ONLINE" bios.log
          grep -F "SOVRN ENGINE ONLINE" uefi.log
          echo "Smoke PASS"

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gate2a-artifacts
          path: |
            iso/sovrn.iso
            bios.log
            uefi.log
