name: Gate 2A — Smoke (BIOS+UEFI)

on: [push]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install host deps (QEMU + OVMF)
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq qemu-system-x86 ovmf xorriso

      - name: Build tool image
        run: docker build -t sovrn-efi .

      - name: Build BIOS+UEFI and ISO inside container
        run: |
          docker run --rm -v "$PWD":/work -w /work --entrypoint /bin/sh sovrn-efi -euxc '
            scripts/buildinfo.sh
            scripts/build_bios.sh
            scripts/esp_sync.sh
            scripts/mkiso.sh
          '
          ls -lh iso/sovrn.iso out/stage2.bin boot/BOOTX64.EFI

      - name: BIOS smoke (legacy)
        run: |
          qemu-system-i386 -machine pc,accel=tcg -no-reboot \
            -serial file:serial-bios.log \
            -cdrom "$PWD/iso/sovrn.iso" -boot order=d || true
          sed -n '1,120p' serial-bios.log || true

      - name: UEFI smoke (OVMF)
        run: |
          CODE=/usr/share/OVMF/OVMF_CODE.fd
          VARS=/usr/share/OVMF/OVMF_VARS.fd
          cp "$VARS" OVMF_VARS.tmp.fd
          qemu-system-x86_64 -machine q35,accel=tcg -no-reboot \
            -serial file:serial-uefi.log \
            -drive if=pflash,format=raw,readonly=on,file="$CODE" \
            -drive if=pflash,format=raw,file=OVMF_VARS.tmp.fd \
            -cdrom "$PWD/iso/sovrn.iso" -boot order=d,menu=off || true
          sed -n '1,120p' serial-uefi.log || true

      - name: Assert banner seen on both paths
        run: |
          set -e
          grep -F "SOVRN ENGINE ONLINE" serial-bios.log
          grep -F "SOVRN ENGINE ONLINE" serial-uefi.log
          echo "Smoke PASS"

      - name: Upload smoke logs
        uses: actions/upload-artifact@v4
        with:
          name: smoke-logs
          path: |
            serial-bios.log
            serial-uefi.log
